from pptx import Presentation
from pptx.util import Inches

def generate_pptx(data: dict, output_path: str) -> str:
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    slides_data = [
        (data.get("idea", "Startup Idea"), "Generated by AI Startup Co-Founder"),
        ("The Problem", data.get("pitch", {}).get("slides", [{}])[1].get("content", []) if len(data.get("pitch", {}).get("slides", [])) > 1 else []),
        ("The Solution", data.get("pitch", {}).get("slides", [{}])[2].get("content", []) if len(data.get("pitch", {}).get("slides", [])) > 2 else []),
        ("Market Opportunity", data.get("pitch", {}).get("slides", [{}])[3].get("content", []) if len(data.get("pitch", {}).get("slides", [])) > 3 else []),
        ("Business Model", data.get("business_model", {}).get("revenue_streams", [])),
        ("Competitive Advantage", data.get("pitch", {}).get("slides", [{}])[5].get("content", []) if len(data.get("pitch", {}).get("slides", [])) > 5 else []),
        ("Go-To-Market Strategy", data.get("pitch", {}).get("slides", [{}])[6].get("content", []) if len(data.get("pitch", {}).get("slides", [])) > 6 else []),
        ("Revenue Forecast", [f"Year 1: {data.get('revenue', {}).get('year1', {}).get('revenue', 'N/A')}", f"Year 2: {data.get('revenue', {}).get('year2', {}).get('revenue', 'N/A')}", f"Year 3: {data.get('revenue', {}).get('year3', {}).get('revenue', 'N/A')}"]),
        ("Funding Ask", data.get("pitch", {}).get("slides", [{}])[10].get("content", []) if len(data.get("pitch", {}).get("slides", [])) > 10 else ["Funding required"]),
    ]
    for title_text, content_items in slides_data:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = title_text
        body = slide.placeholders[1]
        tf = body.text_frame
        tf.text = ""
        for item in content_items:
            p = tf.add_paragraph()
            p.text = item
            p.level = 0
    prs.save(output_path)
    return output_path
